morpho-org/metamorpho

src/MetaMorpho.sol
src/interfaces/IMetaMorpho.sol
test/forge/GuardianTest.sol
test/forge/TimelockTest.sol
test/forge/helpers/BaseTest.sol
test/forge/helpers/IntegrationTest.sol

Reverts morpho-org/metamorpho#240

Revert "Refactor interfaces"

---

src/MetaMorpho.sol

Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/98

Rename the `owner` parameter to `receiver`

---

src/MetaMorpho.sol
test/forge/MetaMorphoInternalTest.sol

Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/101

Renaming `static` -> `simulate` withdraw

---

src/MetaMorpho.sol

Fixes  https://github.com/cantinasec/review-morpho-blue-1/issues/97

Fix: add warning natspec about malicious guardian - issue 97

---

README.md
src/MetaMorpho.sol
src/libraries/ConstantsLib.sol
src/libraries/ErrorsLib.sol
test/forge/TimelockTest.sol
test/metamorpho_tests.tree

Fixes https://github.com/morpho-org/metamorpho/issues/255
This reverts commit ba5eb56afcbbab75c92415298987add2ba0c226b.

Remove timelock expiration

---

src/MetaMorpho.sol

Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/87

Use force approve

---

src/MetaMorpho.sol
test/forge/DeploymentTest.sol

Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/86

Validate `morpho` address in constructor

---

src/MetaMorpho.sol
src/libraries/EventsLib.sol
test/forge/ReallocateWithdrawTest.sol
test/metamorpho_tests.tree

Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/95

Add event in `reallocate`

---

src/MetaMorpho.sol
src/libraries/EventsLib.sol
test/forge/ReallocateWithdrawTest.sol
test/forge/TimelockTest.sol
test/forge/UrdTest.sol

- Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/105
- Fixes #304

refactor(events): add caller

---

src/MetaMorpho.sol

Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/107

Comment flashloan handling

---

src/MetaMorpho.sol

Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/108#issuecomment-1791965416

Fix/ Document roundings maxRedeem - issue 108

---

src/libraries/ConstantsLib.sol

Fixes https://github.com/morpho-labs/metamorpho/issues/252

Min timelock 24 hours

---

src/MetaMorpho.sol
src/interfaces/IMetaMorpho.sol
src/libraries/ErrorsLib.sol
test/forge/MarketTest.sol
test/forge/RoleTest.sol
test/hardhat/MetaMorpho.spec.ts
test/metamorpho_tests.tree

Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/91

Fix: update natspec - issue 91

---

src/MetaMorphoFactory.sol

Fixes https://github.com/morpho-org/universal-rewards-distributor/issues/96

fix: Typographical Errors MM - issue n 07

---

src/interfaces/IMetaMorpho.sol

Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/118

Fix: haromize submittedAt - issue 118

---

src/MetaMorpho.sol
src/interfaces/IMetaMorpho.sol
test/forge/GuardianTest.sol
test/forge/TimelockTest.sol
test/forge/helpers/BaseTest.sol
test/forge/helpers/IntegrationTest.sol

Same as #272 but based on cantina-review

refactor: split interfaces

---

src/MetaMorpho.sol
src/mocks/ERC1820Registry.sol
src/mocks/ERC777Mock.sol
test/forge/FeeTest.sol
test/forge/ReentrancyTest.sol

fix(fee): update last total assets before transferring underlying

---

test/forge/MarketTest.sol
test/forge/ReallocateWithdrawTest.sol
test/forge/RoleTest.sol

feat: update tests

---

src/MetaMorpho.sol
src/MetaMorphoFactory.sol
src/interfaces/IMetaMorphoFactory.sol
src/interfaces/IMorphoMarketParams.sol
test/forge/MetaMorphoFactoryTest.sol

Natspecs are not moved to the interface... Should we?

refactor(interface): add metamorpho factory interface

---

src/interfaces/IMetaMorpho.sol

- Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/f4d93440-228c-461e-8be5-d8e0b42f1fa1

fix(ifc): owner is view

---

src/MetaMorpho.sol

Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/63dbc883-ecf0-4a6a-a844-0cfb015127c9

Add comment on reallocate

---

src/interfaces/IMetaMorpho.sol

Remove outdated comment

---

.github/workflows/certora.yml
.gitignore
certora/README.md
certora/applyMunging.patch
certora/confs/Roles.conf
certora/dispatch/ERC20NoRevert.sol
certora/dispatch/ERC20Standard.sol
certora/dispatch/ERC20USDT.sol
certora/gambit.conf
certora/harness/IMorphoHarness.sol
certora/harness/MetaMorphoHarness.sol
certora/makefile
certora/specs/Roles.spec

This PR implements the base setup of the verification. The given rule is still to verify, and some functions were temporarily filtered out

[Certora] Dev

---

.github/workflows/certora.yml
certora/confs/ConsistentState.conf
certora/harness/MetaMorphoHarness.sol
certora/specs/ConsistentState.spec

Ensures that the (max and min) constants in `ConstantsLib` are respected

[Certora] Consistent State

---

.github/workflows/certora.yml
certora/confs/Immutability.conf
certora/specs/Immutability.spec

Check that the contract is immutable (separate from #396 because it makes no assumption for the proof)

[Certora] Immutability

---

.github/workflows/certora.yml
certora/README.md

[Certora] Switch to stable version of the prover

---

src/mocks/ERC1820Registry.sol

Add SPDX identifier to ERC1820Registry.sol

---

certora/confs/Range.conf
certora/confs/Reverts.conf
certora/confs/Tokens.conf

See [changelog](https://docs.certora.com/en/latest/docs/prover/changelog/prover_changelog.html#august-11-2025)

[Certora] Update to prover v8
