src/MetaMorpho.sol
src/interfaces/IMetaMorpho.sol
src/libraries/EventsLib.sol
src/libraries/PendingLib.sol
test/forge/GuardianTest.sol
test/forge/TimelockTest.sol
test/metamorpho_tests.tree

refactor(timelock): change submittedAt to validAt

---

src/MetaMorpho.sol
src/interfaces/IMetaMorpho.sol
test/forge/ERC4626Test.sol
test/forge/ReallocateIdleTest.sol
test/forge/ReallocateWithdrawTest.sol
test/forge/RoleTest.sol
test/hardhat/MetaMorpho.spec.ts

With this change, the allocator role is responsible for ordering input allocations so as to have sufficient liquidity at each supply step

refactor(reallocate): expect final allocation

---

foundry.toml

The goal is to make so the installation does not mess the git state. Before this PR, if you start from a fresh repository you would have git show some changes on the `foundry.toml` file. Repro: `rm -rf lib && forge install`, and then check that you have changes with `git status`

Add libs explicitly to foundry.toml

---

src/MetaMorpho.sol

- Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/dc29a0e6-64b1-4f9b-a73e-9ce28b7f34a4

docs(fee): add acknowledegement

---

src/MetaMorpho.sol
test/forge/MetaMorphoInternalTest.sol
test/forge/helpers/IntegrationTest.sol

https://morpholabs.slack.com/archives/C02N7CSP91C/p1702569747842329
and fixes #352

Remove automatic supply queue push

---

README.md
src/MetaMorpho.sol

Fixes :
- https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/a29d3775-3516-4013-b78a-69d00f0dc43a
- https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/3442e8f8-d0a2-46bd-83a8-67208038e5f5
- https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/1d74afc9-25a1-4c51-a004-fbaa4ee8f3e3
- https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/47b33a14-c10e-41cf-921e-19236493856a
- https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/0ce3ec22-ab52-4e6a-afed-ab98a7bc1fde
- https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/6a478755-6285-42fe-b0e9-04eb43ba6f2f

Update doc and natspec

---

src/MetaMorpho.sol
src/interfaces/IMetaMorpho.sol
test/forge/GuardianTest.sol
test/forge/MarketTest.sol
test/forge/MetaMorphoInternalTest.sol
test/forge/TimelockTest.sol
test/forge/helpers/IntegrationTest.sol
test/hardhat/MetaMorpho.spec.ts

it saves 10k for the `acceptCap` function (>5%)

perf(setCap): use market params

---

src/MetaMorpho.sol
test/forge/ERC4626Test.sol

Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/637922bd-c38b-4ea0-bb51-a1420a47d088

Fix _withdraw() natspec

---

src/MetaMorpho.sol
test/forge/ERC4626Test.sol

Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/963a0dbd-fcf0-4882-9d07-ac6711667cd8
Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/52649f43-6794-4046-888e-ebaaa7e3d0a4

Fix rounding in max deposit

---

.github/workflows/foundry.yml
src/MetaMorpho.sol
src/interfaces/IMetaMorpho.sol
src/libraries/ConstantsLib.sol
test/forge/ERC4626Test.sol
test/forge/FeeTest.sol
test/forge/helpers/BaseTest.sol

- Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/414d3776-a3c9-450f-aca6-549a7cff2d41

fix(erc4626): make decimals offset adapt

---

src/interfaces/IMetaMorpho.sol

Add comments on lost fees due to bad debt or market forced removals

---

src/MetaMorpho.sol
src/libraries/ErrorsLib.sol
test/forge/ReallocateWithdrawTest.sol
test/forge/TimelockTest.sol

Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/131b79f3-83fc-4674-a222-c5c4dc7d0539
But most importantly, fixes the fact that a withdrawn donation gets taxed from the vault manager
1. If the withdrawn donation corresponds to some liquidity the vault owned formerly, this liquidity gets taxed for no reason (for example: the curator bundles `updateWithdrawQueue` then `reallocate` instead of `reallocate` then `updateWithdrawQueue`)
2. The entrypoint `reallocate` now reverts as soon as at least 1 market of the withdraw queue is broken. The curator no longer can reallocate liquidity across working markets as soon as 1 market is broken: they are forced to `submitMarketRemoval` and cannot reallocate for the duration of the timelock
3. it increases the gas cost of …

fix(reallocate): prevent withdrawing from market not enabled

---

src/MetaMorpho.sol
test/forge/RevokeTest.sol

Apply @QGarchery's suggestion: https://github.com/morpho-org/metamorpho/pull/353/files#r1436881439

refactor: no revert on revoke

---

src/interfaces/IMetaMorpho.sol

Refactor because it is already explained below the different cases where the market can be removed (also the first comment was missing a case)
fixes #362

Simplify comment about removed markets

---

src/MetaMorpho.sol

https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/947a5102-ba21-4b57-8c04-9b737608d74f?q=status%253Anew%252Cdisputed%252Crejected%252Cduplicate%252Cpotentially_duplicate%252Cconfirmed%252Cacknowledged%252Cfixed

Add comment duplicate markets in maxDeposit/Mint

---

src/interfaces/IMetaMorpho.sol

Fixes #316 (by acknowledging it)
discussion: https://morpholabs.slack.com/archives/C02N7CSP91C/p1703775229246109

acknowledge non idempotence of `updateWithdrawQueue`

---

README.md
src/MetaMorpho.sol
src/interfaces/IMetaMorpho.sol

Fixes:
- https://github.com/morpho-org/metamorpho/pull/359#discussion_r1438523800
- https://github.com/morpho-org/metamorpho/pull/371#discussion_r1438549968
- https://github.com/morpho-org/metamorpho/pull/338#discussion_r1438548124
- https://github.com/morpho-org/metamorpho/pull/346#discussion_r1438494502
- arbitrary collateral token for idle market (to make it more like the other parameters)

Fixes Stermi review

---

foundry.toml

Removes the optimizer runs because the factory is too heavy to be deployed with optimizations run

build: update optimizer

---

certora/specs/ConsistentState.spec

The goal of this PR is to prove that a market can't be marked for removal and (have supply cap > 0 or have a pending cap). This is a useful property to make sure that there are no ambiguity as what will happen to that market in the future

[Certora] Forced market removal independence

---

.github/workflows/certora.yml
certora/confs/Immutability.conf
certora/confs/Reentrancy.conf
certora/confs/Reverts.conf
certora/specs/Immutability.spec
certora/specs/Reentrancy.spec

This PR's goals is to prove that there is no possibility of a reentrancy attacks, assuming that:
- Tokens are trusted. This assumption could potentially be relaxed, based on the fact that the accounting does not depend on reentrant calls. In fact, MetaMorpho has been built with this concern in mind, notably to take into account ERC777 tokens. To simplify the verification though, tokens are assumed to not reenter the contract.
- Morpho Blue and Morpho Blue markets are trusted. Morpho Blue is an immutable contract, and thoroughly verified.
Note also that both assumption make sense in the context of timelocked markets: a market (and its corresponding collateral and loan token) can only be added after going through a timelock phase. After a proper analysis during this period, a market could …

[Certora] Reentrancy

---

test/forge/DeploymentTest.sol
test/forge/ERC4626Test.sol
test/forge/MulticallTest.sol
test/forge/TimelockTest.sol
test/forge/helpers/BaseTest.sol
test/forge/helpers/IntegrationTest.sol
test/forge/helpers/InternalTest.sol

MetaMorpho uses Solidity 0.8.21 (strictly). The goal is to have 0.8.24 in the [public allocator](https://github.com/morpho-org/public-allocator) but still be able to reuse Metamorpho's useful test contracts. That means not importing `MetaMorpho` in `IntegrationTest`.
This PR adds a MM-deployer function in `IntegrationTest`. It creates Metamorpho instances using `deployCode`. As with Blue, importers of MM must now have a `MetaMorphoImport.sol` file which adds `MetaMorpho` to the compilation plan.

use deployCode in IntegrationTest so solidity version is not fixed

---

hardhat.config.ts
test/hardhat/MetaMorpho.spec.ts

So the idea is that previously:
- allocation was meant to be all equal on non idle markets, but it wasn't because the idle assets were not reallocated
- withdrawing was rarely hitting more than 1 market
- users were only fresh depositing, not re-depositing
What I did is:
- fix the reallocation bug
- make so that each user interacts twice, first time they deposit a lot and withdraw not much, second time they deposit not much and withdraw a lot (with avg total deposits/withdraw equal for each user). It makes so that when interacting the second time, users are on avg withdrawing from the vault and it at least withdraws from all markets for the last user - so it's closer to prod

test(hardhat): use pyramidal deposits/withdraws

---

certora/specs/ConsistentState.spec
certora/specs/Timelock.spec

This PR:
- implements last point of #412 
- uses the canonical pattern of checking timestamp properties in `Timelock.spec`

[Certora] Implement reviews suggestions

---

certora/confs/MarketInteractions.conf
certora/specs/MarketInteractions.spec

This enables the basic rule_sanity checks for MarketInteractions.  Instead of an invariant it uses a generic rule.

[Certora] Added sanity checks for MarketInteractions

---

certora/confs/ConsistentState.conf
certora/confs/Enabled.conf
certora/confs/Liveness.conf
certora/confs/Range.conf
certora/confs/Reverts.conf

Fix timeouts that were introduced in the new version of the prover

[Certora] Fix timeouts

---

src/interfaces/IMetaMorpho.sol

This PR:
- "documents" the changes done on https://github.com/morpho-org/metamorpho/pull/358
- clarifies that the order of operation matters in `reallocate`, because the extracted amount is used for future (supply) allocations

Reallocate natspec

---

certora/README.md
certora/specs/ConsistentState.spec
certora/specs/Enabled.spec
certora/specs/LastUpdated.spec
certora/specs/Roles.spec
certora/specs/Timelock.spec

Rectify typographical inaccuracies
This PR addresses several typographical errors across various files in the project. The changes improve readability and maintain the professional standard of the documentation and code comments.
Justification
Typographical errors, while minor, can detract from the overall quality of the project. Correcting these errors ensures clarity and professionalism, making the project more accessible and understandable for current and future contributors.

Docs improvements

---

certora/README.md

[Certora] fix typos

---

certora/confs/ConsistentState.conf
certora/confs/DistinctIdentifiers.conf
certora/confs/Enabled.conf
certora/confs/Immutability.conf
certora/confs/LastUpdated.conf
certora/confs/Liveness.conf
certora/confs/MarketInteractions.conf
certora/confs/PendingValues.conf
certora/confs/Range.conf
certora/confs/Reentrancy.conf
certora/confs/Reverts.conf
certora/confs/Roles.conf
certora/confs/Timelock.conf
certora/confs/Tokens.conf
certora/helpers/ERC20Helper.sol
certora/helpers/Util.sol
certora/specs/ConsistentState.spec
certora/specs/LastUpdated.spec
certora/specs/Reverts.spec
certora/specs/Tokens.spec

This PR:
- refactors `Util.sol ` file to only contain ERC20 functions
- updates its morpho-blue dependency, taking advantage of the new Certora utility file introduced in [this PR](https://github.com/morpho-org/morpho-blue/pull/700). This removes the need for `libId`
- moves the `withdrawnAssets` function to the spec
- while we are at it, also formatting .conf files as JSON files
- fixes a timeout in Liveness

[Certora] Update morpho-blue
